### PR TITLE
Added option to enable commentary (again?)

### PR DESCRIPTION
**Pull request by stvnwn**

### CODE REVIEW

**Comment by recordcrash** [comment]
Have you tested this? Can you post some screenshots of it working? I'm not really in a position to test the update myself right now, but if you test it with yours and the previous pull request and it works I'll push it when I get the time.

**Comment by stvnwn** [comment]
On desktop Firefox:
9945d552ade62d54a37e0ca5ccf7b86703f26982

Won't work on Chrome though, because of [incompatibilities](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities). In particular:
> In Chrome, JavaScript APIs are accessed under the `chrome` namespace. In Firefox and Edge, they are accessed under the `browser` namespace.

Have not tested on Android Firefox.

**Comment by recordcrash** [comment]
Thanks a lot! I can't believe you finally managed to make options work, the API documentation was night impossible to understand. I'll try pushing this soon.

**Comment by recordcrash** [comment]
Aww shit. Seems this breaks the extension on the latest version of Chrome. Some "Uncaught ReferenceError: browser is not defined" thing. Apparently the extension has been browser agnostic for now, but the "browser" namespace is a "chrome" namespace in Chrome, and I don't think it's as simple as replacing all instances of browser with chrome, since we use promises for the options, do we not? Chrome uses callbacks.

For now I have kept the extension in Firefox (so 0.3 is out for those users with options and all) and just reuploaded 0.2 to the Chrome web store with the addition of the pesterlog controls as 0.3.1, but if you have any ideas to make the extension truly browser agnostic please submit something. Thanks.

**Comment by stvnwn** [comment]
It'll probably need [Mozilla's webextension-polyfill](https://github.com/mozilla/webextension-polyfill) in order to make it browser agnostic. I'm not sure if you are comfortable with having npm as a dependency to install the polyfill though.

I'll see what I can do later today.

**Pull request merged**
